# Generated by Django 3.2.6 on 2021-08-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidrateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='location',
            field=models.JSONField(default=None, null=True),
        ),
    ]
